### ISSUE TITLE
Investigate https://www.warp.dev/ for shell integration

### ISSUE THREAD

**Issue by andersakerberg** [xencon/aixcl#10]

**Comment by sbadakhc** [comment]
This tool is pretty impressive. We should see if we can use it in the IDE and also to hook it up to a local LLM.

Here is some info about how to do it assuming you already have a local LLM available.

Create a local API server using Flask or FastAPI api that will server the models predictions. The server will act as an intermediary between your commands and the local LLM.

Update your scripts to query the the local API server instead of an external service.


```
from fastapi import FastAPI
from transformers import GPTNeoForCausalLM, GPT2Tokenizer

app = FastAPI()

# Load model and tokenizer
model_name = "EleutherAI/gpt-neo-1.3B"
model = GPTNeoForCausalLM.from_pretrained(model_name)
tokenizer = GPT2Tokenizer.from_pretrained(model_name)

@app.post("/generate")
async def generate(text: str):
    inputs = tokenizer(text, return_tensors="pt")
    outputs = model.generate(**inputs)
    output_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return {"response": output_text}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
```

Then you can run the FastAPI app:

```
python3 app.py

bash
```
You can query this API from your scripts to generate responses from the local LLM. Note that this example is simplified example and additional considerations (performance, security etc.) would be needed for production usage . This way, you can replicate replicate a similar assistant but hosted on your local machine with the model of your choice.
